{% set version = "0.20.0" %}

package:
  name: remage
  version: {{ version }}

source:
  url: https://github.com/legend-exp/remage/archive/v{{ version }}.tar.gz
  sha256: 13a1373749a98ec7e6f8bb5fd23a883123f9d4cc13e4b865397739d11b598404

build:
  skip: true  # [win or py<311]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - geant4 >=11.3
    - bxdecay0 >=1.0.10
    - clhep
    - xerces-c
    - hdf5
    - qt-main
    - fmt
    - cli11
    - magic_enum
    - python
    - pip
    - hatchling
    - hatch-vcs
    - setuptools
    - setuptools-scm

    - legend-pydataobj >=1.16
    - reboost >=0.6
    - pygama >=2.2.3
    - colorlog
    - rich
    - mplhep
    - hist

    # test dependencies
    - pytest >=6
    - awkward
    - hist
    - legend-pygeom-optics >=0.15.0
    - legend-pygeom-hpges >=0.9.0
    - legend-pygeom-tools >=0.0.26
    - matplotlib-base
    - numpy
    - pyg4ometry
  run:
    - python
    - legend-pydataobj >=1.16
    - reboost >=0.6
    - pygama >=2.2.3
    - colorlog
    - rich
    - mplhep
    - hist

test:
  commands:
    - remage --version

about:
  home: https://github.com/legend-exp/remage
  summary: Simulation framework for low-background physics experiments
  description: |
    The remage project aims to deliver a modern Geant4-based C++ library
    designed for efficient simulation of particle physics processes in typical
    low background physics experiments. The library is setup-agnostic,
    requiring users only to define the experimental setup's geometry. Supported
    specification languages include C++, GDML, and others. Once the geometry is
    provided, users can access a comprehensive suite of tools for common tasks,
    such as physics generation and standard output handling.
  license: LGPL-3.0-only AND GPL-3.0-only
  license_file:
    - LICENSE
    - EcoMug_LICENSE
  doc_url: https://remage.readthedocs.io/
  dev_url: https://github.com/legend-exp/remage

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
